### ISSUE TITLE
failure of single cnot circuit and some simple tests

### ISSUE THREAD

**Issue by limbo018** [alexandrupaler/tqec#1]
Hi Alexandru, 

I'm a student in electrical engineering in US  and reading your paper on http://arxiv.org/abs/1604.08621v1. It looks like there are failed cases with the following circuits. 
#1.

circuit.raw

```
c 1 2
```

This is a simple CNOT gate with control qubit 1 and target qubit 2. 
The visual part does not work when I open index.html. 
#2.

circuit.raw

```
t 1
c 1 2 3
```

The second line is supposed to be a toffoli gate of control qubit 1 and two target qubits 2 and 3. 
I got segmentation fault in executing "./convertft circuit.raw.in 0"

The program is compiled under OS X with clang. But I think the problem can also be reproduced under unix with gcc. Hope these inputs are legal to the program. 

Thanks
Yibo

**Comment by alexandrupaler** [comment]
Hello Yibo,

indeed in the current online version of the source code there is bug at multi-control cnots. However, the Toffoli gate should be "T 1 2 3" ( "t" is t gate and "T" is Toffoli).

For #1 circuit, if you open the Development Tools in your browser (Ctrls+Shift+I) and click Console, is there any error message?

Alexandru

**Comment by limbo018** [comment]
Hi Alexandru, 

Thanks for the prompt reply. 
Here's the screenshot of error message. 
![image](https://cloud.githubusercontent.com/assets/6440093/17333043/72a64f9e-5903-11e6-9841-1b22a8b1929d.png)

Best, 
Yibo
