### ISSUE TITLE
Have problem when executing ./localscript.sh

### ISSUE THREAD

**Issue by wayne1204** [alexandrupaler/tqec#2]
Hi Alexandru,

Recently I'm researching topic about TQEC circuits and I've read your paper on https://www.nature.com/articles/srep30600.

I found this GitHub repo and followed the instructions in README. However, I can't successfully build the code and get the error below.
![image](https://user-images.githubusercontent.com/31566889/51493186-780cba00-1def-11e9-8652-eba6b1d8692a.png)
Do you have any clues about this problem? Any help would be greatly appreciated.

Best wishes,
Wayne Huang

**Comment by alexandrupaler** [comment]
Have you managed to compile with "make" outside of the visual folder? Afterwards did "make cpbin" work?

**Comment by wayne1204** [comment]
Yes, I did "make" in the root folder, and since the folder "bin" is missing so I created one.
Below are the files in folder tqec/bin after "make cpbin"
![image](https://user-images.githubusercontent.com/31566889/51498079-405a3e00-1e00-11e9-9504-310a99baa209.png)

**Comment by alexandrupaler** [comment]
I think the error is in my documentation. The first step should be "make all" (according to Makefile)

**Comment by alexandrupaler** [comment]
Did you manage to compile and execute the script? @wayne1204

**Comment by wayne1204** [comment]
Yeah, I've successfully built and executed the code.
Thanks for your help.
By the way, how can I change the input circuit?
Is there any document about the circuit format?

**Comment by alexandrupaler** [comment]
Good to hear that it worked.

The format is not documented, but you can have a look in circconvert.cpp . You can use T for Toffoli, t for T gate, h for Hadamard, c for CNOT, p for Phase gate. 

The first two lines in the file are regarding the number of input and output wires (they are equal) and the states these are initialised (you can use "-" for default)

I did not find the time to document this format, but will potentially do it soon

**Comment by wayne1204** [comment]
Thanks for your generous help! @alexandrupaler 
However, I'm still confused with the **universal gate set** in TQEC.
Since some paper said that TQEC needs to be decomposed into Cliffoed+T form, which seems to differ from the gate set {CNOT, V, P, T} in the paper.

**Comment by alexandrupaler** [comment]
The Clifford set is generated by {CNOT, V, P} and then you need the T to get Clifford+T. In other papers call the P gate is called S. The gates P and V are the square roots of Z and X respectively, and together can be used to implement the Hadamard gate (H).

**Comment by wayne1204** [comment]
Oh, I see.
Thanks a lot!
